### ISSUE TITLE
Add lerna exec

### ISSUE THREAD

**Issue by richardkazuomiller** [ghiscoding/lerna-lite#134]
### Motivation / Use Case
`lerna exec` makes it easy to run a command in every package in a repo. `lerna run` can cover most cases, but if we want to run  a simple command like `rm -rf ./lib` in every package, or a subset of packages with `--scope`, it would be easier to migrate from Lerna if `lerna exec` was also part of lerna-lite.

### Expected Behavior
Same behavior as Lerna's `lerna exec "my-command"`

**Comment by ghiscoding** [comment]
I don't see the need to add `exec` when the only thing you would need to do is add an npm script in each package and use Lerna-Lite `run`. but anyway I wouldn't oppose to receive a PR for it and make it optional like `run` is, but just don't expect me to do it since I don't see the need.

**Comment by richardkazuomiller** [comment]
@ghiscoding Thanks. What I did was I wrote a script to automatically add new scripts to all of the packages in the monorepo, which works fine, but is a bit of work to set up and requires explanation for other contributors to the project. `exec` is pretty commonly used, I think, so if would be much easier for people to migrate if it is added 😄. I haven't looked at the internals at all yet, but I will give it a try and make a PR if I can.

**Comment by ghiscoding** [comment]
Since this can help in migrating, I actually decided to take a look at it and got it working in one long but productive evening yesterday, the leftover (which is the much longer part) will be to fix all failing unit tests and add proper coverage, I'll probably have something by next week. This will become another optional package to keep the lib Lite, stay tuned 😉 

However, I don't wish to add any other commands, apart from maybe Lerna [info](https://github.com/lerna/lerna/tree/main/commands/info#readme) which seems quite small and could be useful when opening new issues.

**Comment by ghiscoding** [comment]
done and available in newest release [v1.1.0](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.1.0)

**Comment by richardkazuomiller** [comment]
@ghiscoding You are amazing!

**Comment by eric-burel** [comment]
> I don't see the need to add `exec` when the only thing you would need to do is add an npm script in each package and use Lerna-Lite `run`. but anyway I wouldn't oppose to receiving a PR for it (it would have to optional like `run` is), but just don't expect me to do it since I really don't see the need.

This is necessary in monorepo context, you cannot add scripts in each package this way, it's too hard to maintain. For instance I use that for "depcheck": https://github.com/VulcanJS/vulcan-npm/blob/main/package.json
I've requestd this feature in Turborepo as well: https://github.com/vercel/turborepo/discussions/375

Many thanks for releasing this feature, it works just perfect, with all arguments!
