### ISSUE TITLE
Can't publish because same version (using preid)

### ISSUE THREAD

**Issue by natew** [ghiscoding/lerna-lite#140]
### Describe the bug

Published version is `1.0.0-canary.204+c205abc9`.

Running `lerna publish --canary --preid canary --force-publish` it wants to publish `1.0.0-canary.204+2623907d`.

npm fails with:

```
lerna-lite ERR! E403 You cannot publish over the previously published versions: 1.0.0-canary.204.
lerna-lite ERR! E403 You cannot publish over the previously published versions: 1.0.0-canary.204.
```

### Reproduction

On this branch `yarn publish:canary`: https://github.com/tamagui/tamagui/pull/41

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0-alpha.68"
}
```
</p></details>

### Environment Info

```shell
lerna-lite notice cli v1.1.1

 Environment info:

  System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - ~/Library/Caches/fnm_multishells/12323_1651466856815/bin/node
    Yarn: 3.2.0 - ~/Library/Caches/fnm_multishells/12323_1651466856815/bin/yarn
    npm: 8.3.1 - ~/Library/Caches/fnm_multishells/12323_1651466856815/bin/npm
  Utilities:
    Git: 2.34.1 - /opt/homebrew/bin/git
```

### Used Package Manager

yarn >= 2.x

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by z3dev** [comment]
@natew what's the goal? pre-release?

**Comment by ghiscoding** [comment]
Please note that even though I created this fork, I don't know all the code that well and I especially don't know all of its options and usage. Basically, I'm sorry but I don't think that I can help much here because I actually never used the canary option myself. I did however migrate all unit tests related to that option [publish-canary.test](https://github.com/ghiscoding/lerna-lite/blob/main/packages/publish/src/__tests__/publish-canary.test.js) and they're all passing. 

I would suggest to look at Lerna's [issue](https://github.com/ghiscoding/lerna-lite/blob/main/packages/publish/src/__tests__/publish-canary.test.js) to see if you find anything similar to your problem.

**Comment by diegoquintanauala** [comment]
hello! sorry, my english is horrible but i want to tell my experience with yarn and lerna.

In the publish:canary script, can you try running it with npm instead of yarn?

Because when trying to post it points to the thread yarn registry

**Comment by ghiscoding** [comment]
Also found this Lerna [issue #3084](https://github.com/lerna/lerna/issues/3084) which seems similar since he also uses preid

**Comment by ghiscoding** [comment]
this [solution](https://github.com/lerna/lerna/issues/1893#issuecomment-602691974) would probably help with this and it does seem to be a bug in Lerna that might not have been fixed yet

**Comment by ghiscoding** [comment]
in [v4.0](https://github.com/lerna-lite/lerna-lite/releases/tag/v4.0.0), the `+` symbol was replaced with the `.` making distinctive versions and so this should not longer be an issue anymore
