### ISSUE TITLE
`--sync-workspace-lock` not working with `lerna version`

### ISSUE THREAD

**Issue by johnsoncodehk** [ghiscoding/lerna-lite#214]
### Describe the bug

I'm not sure if this is design behavior, `--sync-workspace-lock` maybe only is only meaningful for `lerna release`, but I don't have a new version to release yet so I can't try with `lerna release`. 🤣

### Expectation

Run `lerna version --sync-workspace-lock` should changes pnpm-lock.yaml.

### Reproduction

Clone https://github.com/johnsoncodehk/volar and run and run `$ pnpm i && npm run version:test`.

### Lerna config and logs

<details><summary>lerna.json</summary><p>

```json
{
	"packages": [
		"extensions/*",
		"packages/*"
	],
	"version": "0.37.3"
}
```
</p></details>

### Environment Info

```shell
| Executable        | Version |
| ----------------- | ------- |
| `lerna --version` | 4.0.0 |
| `npm --version`   | 8.5.5 |
| `yarn --version`. | 1.22.4 |
| `pnpm --version`  | 7.0.0 |
| `node --version`  | v16.15.0 |
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/lerna-lite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/lerna-lite/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
@johnsoncodehk I think I find your issue, you're simply missing the `npmClient` 😉 
Can you please add `"npmClient": "pnpm"` to your `lerna.json` and see if that does it. There's a big chance it will, more info in [`lerna.json`](https://github.com/ghiscoding/lerna-lite/wiki/lerna.json#lernajson) Wiki 😄

**Comment by johnsoncodehk** [comment]
@ghiscoding It works for me, thank you!

Wiki is great, I just thought it would work without config because old lerna didn't have npmClient also changed yarn.lock, but I agree it's better to set it explicitly. Maybe you could consider throwing an error when `--sync-workspace-lock` doesn't find the corresponding lock file, in case people don't know to set it.

Off topic: Before you make lerna-lite, I also have the same idea (same package name, same project scope with less features and depends!), so when I saw lerna-lite I just knew what it was made for, and I'm really grateful you made it!

**Comment by ghiscoding** [comment]
Yeah I had conversation with others to possibly auto-detect which lock file to update but since `npmClient` exist and should be preferred anyway without requiring any for loop of any kind then I thought it would be ok.

Did you happen to see an error in the console while running the command or in the `lerna-debug.log` mentioning that it didn't find the lock file? I would expect it to show the following error (by the way, it's just a console error, it won't stop the flow)
```sh
we could not sync or locate "package-lock.json" from path ...."
```
I could tweak the error message a bit more to tell the user that he might have forgot to change `npmClient`, something along the line of 
```sh
we could not sync or locate "package-lock.json" by using "npm" from path "xyz" 
Note: if you were expecting a different lock file, please make sure to update "npmClient" in "lerna.json" file.
```
So I have 2 ways to help a bit more in the future, 
1. I could provide a better error message in the console
2. or I could also do the loop to auto-detect if every lock file type exist and which one to use/update

Let me know what you think is best, you are my biggest user after all (the lib with the most stars), happy to have you on board 😉

**Comment by johnsoncodehk** [comment]
I always prefer 1. if I can, because more explicit behavior means less code, less documentation, and more predictability to me. But I believe peoples have different expectations.

> Let me know what you think is best, you are my biggest user after all (the lib with the most stars), happy to have you on board 😉

I'm think large projects just can't move so fast to migrate to lerna-lite in a short period of time, but I would definitely recommend lerna-lite to others. 😉

**Comment by ghiscoding** [comment]
@johnsoncodehk 
I have updated error message, it should be clearer now (not yet released though).

I was just curious to know if you were using the pnpm [`workspace:`](https://pnpm.io/workspaces#workspace-protocol-workspace) protocol in Volar, I didn't see it in the couple of packages that I looked into. So I just wanted to point out that Lerna-Lite does support `workspace:` protocol, in case you missed it 😉 It's getting more stable every release, even more so with this new sync lock file flag to help with the use of workspace protocol.

> Off topic: Before you make lerna-lite, I also have the same idea (same package name, same project scope with less features and depends!), so when I saw lerna-lite I just knew what it was made for, and I'm really grateful you made it!

Thanks for the kind words, glad to know that my approach was correct and that I wasn't the only one with that in mind 😃 
Have a nice day 🌞

**Comment by johnsoncodehk** [comment]
I don't know it, but I think I will not use `workspace:` after take a look, because it's only works for pnpm publish, but the pakcages in https://github.com/johnsoncodehk/volar/tree/master/extensions are is use vsce not pnpm to release. If I only use `workspace:` for https://github.com/johnsoncodehk/volar/tree/master/packages packages it brings some inconsistencies and confusion to the project. But thanks for let me know it!

> Thanks for the kind words, glad to know that my approach was correct and that I wasn't the only one with that in mind 😃

Please trust your decision more in the repo. :)
