### ISSUE TITLE
Add contributors badges to Github Releases

### ISSUE THREAD

**Issue by StarpTech** [ghiscoding/lerna-lite#248]
### Clear and concise description of the problem

As titled. Example https://github.com/wundergraph/wundergraph/releases/tag/v0.94.0

### Suggested solution

See https://github.com/wundergraph/wundergraph/releases/tag/v0.94.0

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/lerna-lite/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://github.com/ghiscoding/lerna-lite#readme).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ghiscoding** [comment]
that's a good suggestion but I wouldn't know how to add this suggested feature, if you know how to please provide a PR

**Comment by StarpTech** [comment]
This is happening automatically as soon as we reference the contributor by name in the changelogs.

**Comment by ghiscoding** [comment]
I'm not exactly sure what you mean but the release seems to be created in this file [create-release.ts](https://github.com/ghiscoding/lerna-lite/blob/main/packages/version/src/lib/create-release.ts) which then calls [github-client.ts](https://github.com/ghiscoding/lerna-lite/blob/main/packages/core/src/git-clients/github-client.ts) when the repo is on GitHub. It's getting his info from Octokit, so I don't know if that can pull the contributors but some of these 2 files must be updated to do what you want to do

**Comment by ghiscoding** [comment]
it might be doable to change the changelog creation format according to [conventional-changelog/git-raw-commits](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/git-raw-commits) we can provide the `format` option and the default is `%B` (which is the commit body) but if we change it to `'%B (@%cn)'` then we would get something similar to your format, I tried the command on another repo and got this
```sh
$ git log --format='%B (@%cn)' ccbf7bf223e3e316fc6222343114435264b72a15^!
chore(release): 4.2.4
 (@ghiscoding)
```
the git raw commit is used in the changelog creation here

https://github.com/ghiscoding/lerna-lite/blob/e21405196247a765ee72c14850e34a1e3af12c53/packages/core/src/conventional-commits/update-changelog.ts#L48

so perhaps that could be changed with the new format option

**Comment by ghiscoding** [comment]
@StarpTech you can review the PR #249, it's a bit hacky to circumvent the missing feature from `conventional-changelog` itself and you can read all about it in the PR. However also please note that I would prefer to wait before to merge it at the same time as your own PR to release all of the new features at the same time. Thanks
