### ISSUE TITLE
ts-node should be `devDependencies`

### ISSUE THREAD

**Issue by azu** [ghiscoding/lerna-lite#75]
## Your Environment

| Executable        | Version |
| ----------------- | ------- |
| `lerna --version` | 1.0.4 |
| `npm --version`   | 8.3.0 |
| `yarn --version`  | 3.2.0 |
| `node --version`  | v16.13.0 |

| OS   | Version |
| ---- | ------- |
| NAME | VERSION |
| macOS      | 12.3 |

### Describe the Bug

ts-node should be `devDependencies`, but follow packages has it as `dependencies`

https://github.com/ghiscoding/lerna-lite/blob/c833bad589258e4a1635d1d93252010670640642/packages/core/package.json#L77
https://github.com/ghiscoding/lerna-lite/blob/c833bad589258e4a1635d1d93252010670640642/packages/publish/package.json#L60

Yarn v3 show following warning when install `@lerna-lite/cli`

```
➤ YN0002: │ @lerna-lite/core@npm:1.0.4 doesn't provide @types/node (pb19ee), requested by ts-node
➤ YN0002: │ @lerna-lite/core@npm:1.0.4 doesn't provide typescript (p785e5), requested by ts-node
➤ YN0002: │ @lerna-lite/publish@npm:1.0.4 doesn't provide @types/node (p8fb40), requested by ts-node
➤ YN0002: │ @lerna-lite/publish@npm:1.0.4 doesn't provide typescript (p525db), requested by ts-node
```

### Steps to Reproduce (for bugs)

1. `yarn set version stable`
2. `yarn add @lerna-lite/cli`

```
yarn add @lerna-lite/cli
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @lerna-lite/core@npm:1.0.4 doesn't provide @types/node (pb19ee), requested by ts-node
➤ YN0002: │ @lerna-lite/core@npm:1.0.4 doesn't provide typescript (p785e5), requested by ts-node
➤ YN0002: │ @lerna-lite/publish@npm:1.0.4 doesn't provide @types/node (p8fb40), requested by ts-node
➤ YN0002: │ @lerna-lite/publish@npm:1.0.4 doesn't provide typescript (p525db), requested by ts-node
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 218ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 245ms
➤ YN0000: Done with warnings in 0s 629ms
```

### Expected Behavior

No warning on installing it.

### Current Behavior

Show [YN0002 - MISSING_PEER_DEPENDENCY](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency) warning

### Possible Solution

Move `ts-node` to `devDependencies`

**Comment by ghiscoding** [comment]
you're right, would you like to contribute a Pull Request?

**Comment by ghiscoding** [comment]
@azu version [1.0.5](https://github.com/ghiscoding/lerna-lite/releases/tag/v1.0.5) was released and it includes both of your PRs, thanks a lot for your help and feedback 😺 

Cheers and Happy Coding 👨‍💻

**Comment by azu** [comment]
Thanks!
