### ISSUE TITLE
Does lerna-lite requires Node.js 16 actually?

### ISSUE THREAD

**Issue by azu** [ghiscoding/lerna-lite#77]
## General Topic

lerna-lite requires Node.js >=16.11.0

https://github.com/ghiscoding/lerna-lite/blob/c833bad589258e4a1635d1d93252010670640642/packages/cli/package.json#L31-L34

npm ignore `engines` by default.
yarn follow `engines` by default.

- [Prevent npm install for not supported Node.js versions | Stefan Judis Web Development](https://www.stefanjudis.com/today-i-learned/prevent-npm-install-for-not-supported-node-js-versions/)

As a result, Node.js 14 + Yarn project can not install `@lerna-lite/cli` package with default configuration.

### Your Environment

| Software             | Version(s) |
| -------------------- | ---------- |
| Lerna-Lite           | 1.0.4        |
| NodeJS               | 14       |
| TypeScript           | x.y        |

### Context or Topic

I've used lerna for tools or libraries that supports Node.js LTS.
It means that my project run tests on Node.js 12, 14, 16.

Lerna and Lerna-lite are for publishing, but it will be installed on setup in most case.
It means that root `package.json` will includes `@lerna-lite/cli` as devDependencies.
As a result, `yarn install` fail to install `@lerna-lite/cli` on Node.js 12 and 14.

Example test configuration.
https://github.com/secretlint/secretlint/blob/a14c416c51207cf5b09cd6ea7421c903a9afd9da/.github/workflows/test.yml#L22-L39

### Expected Behavior

As possible, support Node.js LTS.

📝 Node.js 12 LTS will be end of life at 2022-04-30.
https://nodejs.org/en/about/releases/
It is reasonable that still drop support Node.js 12.

### Current Behavior

`yarn add @lerna-lite/cli` throw an error on Node.js 14.

```
❯ node -v
v14.18.1
❯ yarn -v
1.22.17
❯ yarn add @lerna-lite/cli
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @lerna-lite/core@1.0.4: The engine "node" is incompatible with this module. Expected version ">=16.11.0". Got "14.18.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

### Possible Solution

Relax `engines` field. 
In my enviroments, `npm run jest` on Node.js 14 passed all tests.

```diff
  "engines": {
-    "node": ">=16.11.0",
+    "node": ">=14.13.1",
    "npm": ">=8.0.0"
  },
```

📝 npm 8 has supported Node.js >=12. Source: [Release v8.0.0 · npm/cli](https://github.com/npm/cli/releases/tag/v8.0.0)
📝 `"node": ">=14.13.1"` means [Pure ESM support](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)

**Workaround**

Yarn support [--ignore-engines](https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) flag.
This flag skip `engines` checks.

It can be used as a workaround.

- [fix(monorepo): use lerna-lite instead of lerna by azu · Pull Request #250 · secretlint/secretlint](https://github.com/secretlint/secretlint/pull/250)

**Comment by ghiscoding** [comment]
the project itself is built with NPM Workspace, so it needs at least NPM 8. It would probably work with Node 14, you can contribute a Pull Request if you wish.

Side note, I'm not using any of the Pure ESM package (dependencies) that you are referring to, I couldn't find the correct way to use them with TypeScript, that could be another enhancement for the lib in the future

**Comment by azu** [comment]
I've submited a PR https://github.com/ghiscoding/lerna-lite/pull/78
